import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavigationBar from "./NavigationBar";
import AuthProvider from "./auth/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dim">

      <body className={`${inter.className}`} >
        <AuthProvider>

          <NavigationBar />
          <main className="p-3">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
